name: Check PR Title Format

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - main

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    outputs:
      is_valid: ${{ steps.check-pr-title.outputs.is_valid }}
    steps:
      - name: Check PR Title
        id: check-pr-title
        uses: actions/github-script@v7
        with:
          script: |
            const prTitle = context.payload.pull_request.title;
            const pattern = /^\[[^\]]+\]\[[^\]]+\] .+/;
            const isValid = pattern.test(prTitle);
            core.setOutput('is_valid', isValid.toString());

            if (!isValid) {
              core.setFailed(`❌ PR title "${prTitle}" does not match the required pattern. Make sure it starts with two sets of square brackets and a summary.`);
            } else {
              core.info(`✅ PR title "${prTitle}" matches the pattern.`);
            }
