name: Linting & Formatting

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

  workflow_run:
    workflows:
      - Check PR Title Format
    types: [completed]

jobs:
  debug:
    runs-on: self-hosted
    steps:
      - name: Echo
        run: |
          echo "${{github.event.workflow_run.conclusion}}"
